version: "3"

networks:
  test:
    external:
      name: test

services:
  nodeapp:
    image: aditya/node-app:latest
    ports:
      - 4000:4000
    networks:
      test:
        aliases:
          - nodeapp
